#!/usr/bin/env python3
"""Fuse the whole port into one buildable C file: build/tetris_single.c

    python3 tools/amalgamate.py
    cc -O2 build/tetris_single.c -o tetris $(pkg-config --cflags --libs sdl2) -lm
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADERS = ["video.h", "input.h", "assets.h", "audio.h", "game.h"]
SOURCES = ["assets.c", "video.c", "audio.c", "input.c", "game.c", "main.c"]

LOCAL_INC = re.compile(r'^\s*#\s*include\s+"([^"]+)"')


def strip_local_includes(text, keep_vendor=False):
    out = []
    for line in text.splitlines():
        m = LOCAL_INC.match(line)
        if m:
            if keep_vendor and "stb_image" in m.group(1):
                out.append('#include "../vendor/stb_image.h"')
            continue
        out.append(line)
    return "\n".join(out)


def main():
    parts = ["/* tetris_single.c — amalgamated build of the whole port.",
             " * Generated by tools/amalgamate.py; do not edit. */"]
    for h in HEADERS:
        parts.append(f"\n/* ==== src/{h} ==== */")
        parts.append(strip_local_includes((ROOT / "src" / h).read_text()))
    for c in SOURCES:
        parts.append(f"\n/* ==== src/{c} ==== */")
        parts.append(strip_local_includes((ROOT / "src" / c).read_text(),
                                          keep_vendor=True))

    out = ROOT / "build" / "tetris_single.c"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(parts) + "\n")
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    sys.exit(main())
